FROM debian:trixie-backports

RUN mkdir -p /home/glpi

WORKDIR /home/GLPI

RUN apt update && apt install -y lsb-release ca-certificates curl && \
    curl -sSLo /tmp/debsury.gpg https://packages.sury.org/php/apt.gpg && \
    mkdir -p /etc/apt/keyrings && \
    mv /tmp/debsury.gpg /etc/apt/keyrings/sury-php.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/sury-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/sury-php.list && \
    apt-get update


RUN apt install apache2 mariadb-server php-cli php-fpm php-mysql php-json php-gd php-curl php-intl php-zip php-xml php-mbstring php-ldap php-cas php-apcu php-xmlrpc php-cas php-imap php-bz2 -y

CMD [ "mysqld" ]

CMD ["apachectl"]

